apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: test-pod
  name: {{.Values.podname}}
spec:
  containers:
  - command:
    - sleep
    - "1000"
    image: busybox
    name: test-pod
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
